#!/bin/bash

: << =cut

=cut

check_autoconf() {
        echo "yes"
}

print_config() {
  echo 'multigraph iota_jre'
  echo 'graph_title Iota JRE usage'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_vlabel Memory in MBytes'
  echo 'graph_category Iota'
  echo 'graph_info This graph shows the used memory by JRE of the node'

  echo 'jreFreeMemory.label free'
  echo 'jreFreeMemory.type GAUGE'
  echo 'jreFreeMemory.min 0'
  echo 'jreMaxMemory.label max'
  echo 'jreMaxMemory.type GAUGE'
  echo 'jreMaxMemory.min 0'
  echo 'jreTotalMemory.label total'
  echo 'jreTotalMemory.type GAUGE'
  echo 'jreTotalMemory.min 0'

  echo 'multigraph iota_neighbors'
  echo 'graph_title Iota node neighbors'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_vlabel Neighbors'
  echo 'graph_category Iota'

  echo 'neighbors.label neighbors'
  echo 'neighbors.type GAUGE'
  echo 'neighbors.min 0'

  echo 'multigraph iota_milestone'
  echo 'graph_title Iota milestones'
  #echo 'graph_args --base 1000'
  echo 'graph_vlabel Milestone'
  echo 'graph_category Iota'

  echo 'latest.label latest milestone index'
  echo 'latest.type GAUGE'
  echo 'latestSolid.label latest solid milestone index'
  echo 'latestSolid.type GAUGE'

  echo 'multigraph iota_tx'
  echo 'graph_title Iota node status'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_vlabel Value'
  echo 'graph_category Iota'

  echo 'tips.label Tips'
  echo 'tips.type GAUGE'
  echo 'tips.min 0'
  echo 'transactions.label transactions to request'
  echo 'transactions.type GAUGE'
  echo 'transactions.min 0'

  exit 0
}

print_data() {
        curl http://localhost:14265   -X POST   -H 'Content-Type: application/json'   -H 'X-IOTA-API-Version: 1'   -d '{"command": "getNodeInfo"}' -s | jq --raw-output '"multigraph iota_jre","jreFreeMemory.value " + (.jreFreeMemory | tostring),"jreMaxMemory.value " + (.jreMaxMemory | tostring),"jreTotalMemory.value "+(.jreTotalMemory | tostring),"multigraph iota_neighbors","neighbors.value "+(.neighbors|tostring),"multigraph iota_milestone","latest.value "+(.latestMilestoneIndex|tostring),"latestSolid.value "+(.latestSolidSubtangleMilestoneIndex|tostring),"multigraph iota_tx","tips.value "+(.tips|tostring),"transactions.value "+(.transactionsToRequest|tostring)'
}

# Parse arguments, run correct function
case $1 in
    "autoconf")
        check_autoconf
        ;;
    "config")
        print_config
        ;;
    *)
        print_data
        ;;
esac
